completed script tag-Troy Edwards
TroyEdwards41/javascript-prep-1124-code-solutions pull request #3
Opened 2024-11-18 23:56 UTC by TroyEdwards41

<img width="1440" alt="Screenshot 2024-11-18 at 6 31 16 PM" src="https://github.com/user-attachments/assets/a32a0e54-f635-4005-88fa-d52143cbac6f">

2024-11-18 23:59 UTC, shawnkost requested changes
One change here Troy!

2024-11-18 23:59 UTC, shawnkost commented on prep-html-script-tag/index.html
> +      console.log('I have added script file via the src attribute!');
This console log should go inside of your `main.ts` fike, and not in-between the script tags

2024-11-19 02:26 UTC, TroyEdwards41 commented
Shawn I made the changes but I'm not seeing if it reflected them

2024-11-19 17:01 UTC, shawnkost requested changes

2024-11-19 17:01 UTC, shawnkost commented on prep-html-script-tag/index.html
>        console.log('I have added script file via the src attribute!');
It looks like you still have your `console.log` directly in-between your opening and closing `<script>` tag. You should have created a `main.js` file, and you need to move this `console.log` into that `main.js` file.

2024-11-21 23:07 UTC, TroyEdwards41 commented
<img width="1440" alt="Screenshot 2024-11-21 at 7 23 41 AM" src="https://github.com/user-attachments/assets/e7bc043f-d136-426a-80cb-e1e3a2d63971">

2024-11-22 21:42 UTC, robgmerrill approved these changes
👍

2024-11-22 21:44 UTC, merged